CREATE DATABASE RESERVANATURAL;

CREATE TABLE `reservanatural`.`animal` (
  `idave` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Imagen` VARCHAR(200) NULL,
  `Descripcion` VARCHAR(300) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idave`));

ALTER TABLE `reservanatural`.`animal` 
CHANGE COLUMN `Descripcion` `Descripcion` VARCHAR(50000) NULL DEFAULT NULL ;

INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('1', 'Águila harpía (Harpia harpyja)', 'imagenes/Aves/aguila.png', 'Es una especie de ave accipitriforme de la familia Accipitridae que vive en la zona neotropical. Es el águila más grande del Hemisferio Occidental y del Hemisferio Austral, y la única especie del género Harpia. Su hábitat es el bosque lluvioso. No se reconocen subespecies. s una especie de ave accipitriforme de la familia Accipitridae que vive en la zona neotropical. Es el águila más grande del Hemisferio Occidental y del Hemisferio Austral, y la única especie del género Harpia. ', 'ave');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Águila harpía (Harpia harpyja)', `Imagen` = 'imagenes/Aves/aguila.png', `tipo` = 'Ave' WHERE (`idave` = '1');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('2', 'Colibrí (Trochilinae)', 'imagenes/Aves/colibri.png', 'Los troquilinos (Trochilinae) son una subfamilia de aves apodiformes de la familia Trochilidae, conocidas comúnmente como picaflores, colibríes, quindes, tucusitos, chupamirtos, chuparrosas, huitzitzilin (idioma náhuatl), mainumby (idioma guaraní) o guanumby. Conjuntamente con las ermitas, que pertenecen a la subfamilia Phaethornithinae, conforman la familia Trochilidae que, en la sistemática de Charles Sibley, se clasifica en un orden propio: Trochiliformes, independiente de los vencejos del orden Apodiformes. La subfamilia Trochilinae incluye más de 100 géneros que comprenden un total de 330 a 340 especies. Estos pájaros son originarios del continente americano. Antaño se los mató por miles a fin de decorar los sombreros femeninos,1​ lo que posiblemente llevó al exterminio de varias especies.  Los colibríes están entre los pájaros más pequeños que existen. La especie de tamaño más reducido es el colibrí zunzuncito o elfo de las abejas (Mellisuga helenae), que con su pico y cola mide apenas unos 5,5 centímetros, exclusivo de Cuba.3​ La especie más grande, el llamado colibrí gigante (Patagona gigas), mide unos 25 cm. La mayoría de los colibríes presenta un plumaje muy colorido, generalmente de color verde metálico. El cuello de los machos es frecuentemente rojo brillante, azul o verde esmeralda. Una característica especial de los colibríes es el pico, que diverge casi siempre de especie en especie. El colibrí pico espada (Ensifera ensifera), por ejemplo, tiene un pico casi tan largo como el cuerpo, de unos 10 cm de longitud.', 'ave');
UPDATE `reservanatural`.`animal` SET `Descripcion`='Es una especie de ave accipitriforme de la familia Accipitridae que vive en la zona neotropical. Es el águila más grande del Hemisferio Occidental y del Hemisferio Austral, y la única especie del género Harpia. Su hábitat es el bosque lluvioso. No se reconocen subespecies. s una especie de ave accipitriforme de la familia Accipitridae que vive en la zona neotropical. Es el águila más grande del Hemisferio Occidental y del Hemisferio Austral, y la única especie del género Harpia. Su hábitat es el bosque lluvioso. ' WHERE `idave`='1';
UPDATE `reservanatural`.`animal` SET `Descripcion`='Los troquilinos (Trochilinae) son una subfamilia de aves apodiformes de la familia Trochilidae, conocidas comúnmente como picaflores, colibríes, quindes, tucusitos, chupamirtos, chuparrosas, huitzitzilin (idioma náhuatl), mainumby (idioma guaraní) o guanumby. Conjuntamente con las ermitas, que pertenecen a la subfamilia Phaethornithinae, conforman la familia Trochilidae que, en la sistemática de Charles Sibley, se clasifica en un orden propio: Trochiliformes, independiente de los vencejos del orden Apodiformes. La subfamilia Trochilinae incluye más de 100 géneros que comprenden un total de 330 a 340 especies. Estos pájaros son originarios del continente americano. Antaño se los mató por miles a fin de decorar los sombreros femeninos,1​ lo que posiblemente llevó al exterminio de varias especies.  Los colibríes están entre los pájaros más pequeños que existen. La especie de tamaño más reducido es el colibrí zunzuncito o elfo de las abejas (Mellisuga helenae), que con su pico y cola mide apenas unos 5,5 centímetros, exclusivo de Cuba.3​ La especie más grande, el llamado colibrí gigante (Patagona gigas), mide unos 25 cm. La mayoría de los colibríes presenta un plumaje muy colorido, generalmente de color verde metálico. El cuello de los machos es frecuentemente rojo brillante, azul o verde esmeralda. Una característica especial de los colibríes es el pico, que diverge casi siempre de especie en especie. El colibrí pico espada (Ensifera ensifera), por ejemplo, tiene un pico casi tan largo como el cuerpo, de unos 10 cm de longitud.' WHERE `idave`='2';
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('3', 'Garza mora (Ardea cocoi)', 'imagenes/Aves/garza_mora.png', 'La garza cuca o garza mora (Ardea cocoi) es una especie de ave perteneciente al clado Ardeidae2​3​ propia de Centro y Sudamérica.', 'ave');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('4', 'Mirlo (Turdus fuscater)', 'imagenes/Aves/mirlo.png', 'La paraulata morera, mirla patinaranja, o mirlo (Turdus fuscater) es una especie de ave paseriforme sudamericana de la familia del género Turdus. Puebla zonas boscosas y de matorral de Venezuela, Colombia, Ecuador, Perú, Bolivia.', 'ave');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('5', 'Pelícano pardo (Pelecanus occidentalis)', 'imagenes/Aves/pelicano.png', 'El pelícano pardo (Pelecanus occidentalis) es una especie de ave pelecaniforme de la familia Pelecanidae que se encuentra en América desde el sur de los Estados Unidos (es el ave símbolo de Luisiana) hasta la Amazonía.', 'ave');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('6', 'Trepatroncos (Dendrocolaptidae)', 'imagenes/Aves/trepatroncos.png', 'Son aves parduzcas o rojizas, que se alimentan principalmente de insectos cazados en los troncos de los árboles. Son pájaros de bosque que anidan en agujeros o hendiduras; ponen 2 o 3 huevos blancos que incuban durante unos quince días. Siguen las colonias de hormigas que salen a recolectar, esperando que los insectos se muevan y los cazan. Se ha calculado que estos pájaros le roban aproximadamente 200 insectos grandes a una colonia de hormigas por día; lo que equivale al 15% de los requisitos de comida diarios de una colonia de hormigas legionarias.', 'ave');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('7', 'Tucán (Ramphastidae)', 'imagenes/Aves/tucan.png', 'Los ranfástidos (Ramphastidae), conocidos comúnmente como tucanes, diotedé o diostedé. Esta familia de aves ranfástidas del orden de los piciformes es muy amplia ya que alberga seis géneros y cuarenta y dos especies diferentes de tucanes. Se caracterizan por poseer un pico muy desarrollado y de vivos colores. Miden entre 18 y 65 cm, siendo el tucán toco (Ramphastos toco) el de mayor tamaño. Están ampliamente distribuido por el continente americano, desde México hasta Argentina y Colombia. Algunas especies prefieren selvas húmedas tropicales de baja altitud, mientras que otras habitan en bosques más templados en cordilleras, a altitudes hasta los 3000 msnm. El nombre de este grupo de aves procede del guaraní: tupí tucana.', 'ave');
INSERT INTO `reservanatural`.`animal` (`tipo`) VALUES ('');

UPDATE `reservanatural`.`animal` SET `Nombre`='Lophogorgia alba', `Imagen`='imagenes/Corales/Lophogorgia_alba.png', `Descripcion`='...', `tipo`='corales' WHERE `idave`='8';
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('9', 'Pocillopora damicornis', 'imagenes/Corales/Pocillopora_damicornisp.png', '...', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('10', 'Psammacora stellata', 'imagenes/Corales/Psammacora_stellata.png', '...', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('11', 'Porites paramensis', 'imagenes/Corales/Porites paramensis.png', '...', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('12', 'Pavona gigantea', 'imagenes/Corales/Pavona gigantea.png', '...', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('13', 'Pavona clavus', 'imagenes/Corales/Pavona clavus.png', 'Pavona clavus es una especie de coral de la familia Agariciidae, y pertenece al grupo de los corales duros, orden Scleractinia. Es coral hermatípico, por lo que, tras la muerte del coral, su esqueleto contribuye a la generación de nuevos arrecifes en la naturaleza. Es una especie, que por su forma de crecimiento, confiere refugio y protección a invertebrados marinos y peces. Al tiempo, que juega un importante papel dando soporte a la base de muchos arrecifes.', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('14', 'Pavona varians', 'imagenes/Corales/Pavona varians.png', '...', 'corales');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Corales/Pavona_clavus.png' WHERE (`idave` = '13');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Corales/Pavona_varians.png' WHERE (`idave` = '14');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Corales/Pavona_gigantea.png' WHERE (`idave` = '12');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Corales/Porites_paramensis.png' WHERE (`idave` = '11');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Corales/Porites_panamensis.png' WHERE (`idave` = '11');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Corales/Pocillopora_damicornis.png' WHERE (`idave` = '9');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Corales/Psammocora_stellata.png' WHERE (`idave` = '10');

INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('15', 'Armadillo (Dasypodidae', 'imagenesMamiferos/armadillo.png', 'Los dasipódidos (Dasypodidae), conocidos comúnmente como armadillos, son una familia de mamíferos placentarios del ordenCingulata. Se caracterizan por poseer un caparazón dorsal formado por placas yuxtapuestas, ordenadas por lo general en filas transversales, con cola bastante larga y extremidades cortas.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('16', 'Ballena jorobada (Megaptera novaeangliae)', 'imagenes/Mamiferos/ballena.png', 'La yubarta o gubarte (Megaptera novaeangliae), también llamada ballena jorobada, es una especie de cetáceo misticetode la familia Balaenopteridae (rorcuales). Es uno de los rorcuales más grandes, los adultos tienen una longitud de 12 a 16 m y un peso aproximado de 36 000 kg. La especie posee una forma corporal distintiva, con aletas pectorales largas y cabeza nudosa. Es un animal acrobático que con frecuencia se impulsa sobre la superficie para luego golpear el agua. Los machos emiten un canto complejo, el cual dura de diez a veinte minutos y se repite por horas cada vez. El propósito del canto no es claro. Sin embargo, parece desempeñar una función en el apareamiento. Se distribuye por todos los océanos y mares del mundo; normalmente migran hasta 25 000 km cada año. Las yubartas se alimentan solamente durante el verano en las regiones polares y migran a aguas tropicales y subtropicales para reproducirse y parir las crías durante el invierno polar. Mientras trascurre el invierno ayunan y subsisten gracias a su reserva de grasa. La especie se alimenta principalmente de kril y peces pequeños; posee un amplio repertorio de métodos para alimentarse, incluyendo la notable técnica de la red de burbujas.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('17', 'Cachalote (Physeter macrocephalus)', 'imagenes/Mamiferos/cachalote.png', 'El cachalote (Physeter macrocephalus) es una especie de mamífero marino del orden Cetacea del suborden Odontoceti. El cachalote es el único miembro del género Physeter y es una de las tres especies vivientes de la familia Physeteridae, junto al cachalote pigmeo y cachalote enano. Es el animal con dientes más grande que existe; los machos pueden crecer hasta 20,5 metros de largo y llegar a pesar más de 50 toneladas. La cabeza mide un tercio de la longitud total del animal y poseen el cerebro más grande entre los animales existentes. La especie se alimenta de calamares y peces, sumergiéndose en su búsqueda a profundidades de hasta tres kilómetros, convirtiéndose en el mamífero marino que se zambulle a mayor profundidad. Su dieta a base de calamares incluye a las especies más grandes: el calamar gigante y el calamar colosal. Es el depredador viviente más grande y posiblemente el mayor que haya existido, no por el hecho de alimentarse de otros animales (lo cual también es cierto en todos los cetáceos, incluyendo las grandes ballenas), sino por realizar depredación activa sobre animales autónomos. El chasquido producido por el cachalote es el sonido más intenso producido por animal alguno, pero su función se desconoce (aunque se cree que lo usa como sonar y como un medio para aturdir a sus presas). Este cetáceo vive en grupos en los cuales las hembras y sus crías están separados de los machos más viejos que vagan solitarios; las hembras cooperan entre sí para proteger y alimentar a sus retoños. Dan a luz de cada tres a seis años una sola cría y su cuidado se prolonga por más de una década. Son animales muy longevos pudiendo alcanzar fácilmente los setenta años.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('18', 'Comadreja de agua (Chironectes minimus)', 'imagenes/Mamiferos/comadreja.png', 'La cuica de agua (Chironectes minimus) es una especie de marsupial didelfimorfo de la familia Didelphidae, la única del géneroChironectes. Es el único marsupial acuático; vive en bancos y barrancas, emergiendo después de atrapar peces, crustáceos y otros animales acuáticos, que comerá en el banco. Habita arroyos y en lagos desde México y el Caribe hasta el noreste de la Argentina y el noreste del Uruguay.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('19', 'Mono araña (Ateles)', 'imagenes/Mamiferos/mono.png', 'Los monos araña, maquisapas, marimondas, marimonos, koatás o atelos, es el nombre común de cualquiera de los primatesdel género Ateles («sin dedo pulgar») perteneciente a la familia Atelidae. El nombre Ateles hace referencia a la ausencia de un pulgar oponible en las especies del género; solo cuenta con apéndice vestigial.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('20', 'Oso hormiguero gigante (Myrmecophaga tridactyla)', 'imagenes/Mamiferos/oso_hormiguero.png', 'El oso hormiguero gigante (Myrmecophaga tridactyla), también llamado oso bandera, yurumí  a veces escrito erróneamente en español jurumí u oso palmero es la mayor especie de oso hormiguero. Se encuentra en América Central y Sudamérica. Es el único representante del género Myrmecophaga. Su cuerpo mide entre 100 y 120 cm de longitud y su cola de 60 a 90 cm; pesa de 25 a 39 kg.  El hocico es muy alargado y cónico. La lengua tiene 60 cm de largo y está recubierta por una substancia adherente para capturar los insectos de los que se alimenta. Carece de dientes. El pelo del tronco, de color castaño o grisáceo, con una V negruzca y líneas blancas, es corto, excepto en el lomo, en el que se observa una crin, que se une con el muy abundante pelambre de la cola, que presenta bandas plateadas y tonos castaños, negros y grisáceos. El oso hormiguero gigante posee un hocico alargado y convexo, adaptado especialmente para su alimentación. Posee pelaje de color amarillo dorado y tiene una especie de chaleco negro en el lomo, el vientre y los hombros. Presenta cola prensil peluda en la base y pelada en la punta y 4 garras poderosas y largas en las patas delanteras y 5 pequeñas en las traseras. Un ejemplar adulto puede alcanzar 2 metros de longitud desde la punta del hocico hasta la punta de la cola; tiene una lengua de hasta 50 cm de longitud, su vista es débil aunque tiene bastante desarrollados los otros sentidos, es edentado (carece de dientes), se alimenta de hormigas y termitas, entre sus parientes filogenéticos actuales los más próximos son los armadillos y los perezosos. En el 2015 está en grave peligro de extinción, además de la caza por parte del ser humano también suelen ser muertos por destrucción del hábitat.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('21', 'Perezoso bayo (Bradypus variegatus)', 'imagenes/Mamiferos/perezoso.png', 'El perezoso bayo (Bradypus variegatus) es una especie de perezoso tridáctilo de la familia Bradipodidae, perteneciente al orden Pilosa, propia de Centroamérica, México1 y Sudamérica. Es la especie más distribuida y común del grupo, hallándose en muchos y diferentes ambientes, incluyendo selvas siempreverdes, bosques secos y áreas naturales profundamente perturbadas. Es solitario, nocturno y diurno, alimentándose de hojas de muchas especies de árboles. La hembra emite un lamento fuerte, estridente, durante la estación de apareamiento para atraer machos. Es un alarido que suena onomatopeycivamente como un \"ay ay\" y por tal motivo ha recibido este nombre de parte de varias etnias que habitan o habitaban su hábitat.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('22', 'Puma (Puma concolor)', 'imagenes/Mamiferos/puma.png', 'El puma, león de montaña, león o pantera (Puma concolor) es un mamífero carnívoro de la familia Felidae nativo de América. Este gran felino vive en más lugares que cualquier otro mamífero salvaje terrestre del continente, ya que se extiende desde el Yukón, en Canadá, hasta el sur de la cordillera de los Andes y la Patagonia, Argentina y Chile en América del Sur. El puma es adaptable y generalista, por lo que se encuentra en los principales biomas de toda América. Es el segundo mayor félido en el Nuevo Mundo, después del jaguar, y el cuarto más grande del mundo, junto con el leopardo y después del tigre, el león y el jaguar. Su tamaño es mayor que el del leopardo de las nieves, aunque está más emparentado con los pequeños felinos, ya que, a diferencia de los grandes felinos del género Panthera, que pueden rugir, el puma ronronea como los felinos menores. Como caza y depredador de emboscada, el puma persigue una amplia variedad de presas. Su principal alimento son los unguladoscomo el ciervo, en particular en la parte septentrional de su área de distribución, pero también caza camélidos como el guanaco y especies tan pequeñas como insectos y roedor. Prefiere hábitat con vegetación densa durante las horas de acecho, pero puede vivir en zonas abiertas. El puma es territorial y tiene una baja densidad de población. La extensión de su territorio depende de la vegetación y de la abundancia de presas. Aunque es un gran depredador, no siempre es la especie dominante en su área de distribución, como cuando compite con otros depredadores como el jaguar. Se trata de un felino solitario que por lo general evita a las personas. Los ataques a seres humanos son raros, aunque su frecuencia ha aumentado en los últimos años.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('23', 'Jaguar (Panthera onca)', 'imagenes/Mamiferos/jaguar.png', 'El jaguar, yaguar o yaguareté  (Panthera onca) es un carnívoro félido de la subfamilia de los Panterinos y género Panthera. Es la única de las cuatro especies actuales de este género que se encuentra en América. También es el mayor félido de América y el tercero del mundo, después del tigre (Panthera tigris) y el león (Panthera leo). Su distribución actual se extiende desde el extremo sur de Estados Unidos continuando por gran parte de América Central y Sudamérica hasta el norte y noreste de Argentina. Exceptuando algunas poblaciones en Arizona (suroeste de Tucson), esta especie ya ha sido prácticamente extirpada en los Estados Unidos desde principios de la década de 1900.  Se encuentra emparentado y se asemeja mucho en apariencia física al leopardo (Panthera pardus), pero generalmente es de mayor tamaño, cuenta con una constitución más robusta y su comportamiento y hábitat son más acordes a los del tigre (Panthera tigris). Está estrechamente asociado a la presencia de agua y destaca, junto con el tigre, por ser un félido al que le gusta nadar. Es fundamentalmente solitario. Caza tendiendo emboscadas, siendo oportunista a la hora de elegir las presas. Es una especie clave para la estabilización de los ecosistemas en los que habita; al ser un superpredador, regula las poblaciones de las especies que captura. Los ejemplares adultos tienen una mordedura excepcionalmente potente, incluso en comparación con otros grandes félidos,  lo que les permite perforar los caparazones de reptiles acorazados como las tortugas y utilizar un método poco habitual para matar: ataca directamente la cabeza de la presa entre las orejas para propinar un mordisco letal que atraviesa el cráneo con sus colmillos alcanzando al cerebro. Panthera onca está calificado en la Lista Roja de la UICN como «especie casi amenazada» y su número está en declive.  Entre los factores que lo amenazan se incluyen la pérdida y la fragmentación de su hábitat. A pesar de que el comercio internacional de ejemplares de esta especie o sus partes está prohibido,  este félido muere con frecuencia a mano de los humanos, especialmente en conflictos con ganaderos. Aunque reducida, su distribución geográfica continúa siendo amplia. A lo largo de la historia, esta distribución le ha otorgado un lugar prominente en la mitología de numerosas culturas indígenas americanas, como los mayas y los aztecas.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('24', 'Jabalí (Pecari tajacu)', 'imagenes/Mamiferos/jabali.png', 'El pecarí de collar (Pecari tajacu), también conocido como taitetú, coyámel (nahuatlismo de coyámetl) saíno, k ´itam,sajino, coche de monte, chancho rosillo, chácharo, báquiro o huangana, es una especie de mamífero artiodáctilo de la familiaTayassuidae. Se encuentra en sabanas y bosques hasta 3000 msnm desde el sur de Estados Unidos hasta Argentina. Presenta una altura de medio metro en la cruz y una longitud de 70 a 110 cm y cola de 2 a 5 cm. Se caracteriza por un pelaje de cerdas castañonegruzcas y una mancha blanca que recuerda a un collar en la base del cuello. En el lomo tiene una cavidad glandular de 12 a 1 cm de la que secreta un aceite de olor almizclado.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('25', 'Zarigüeya común (Didelphis marsupialis)', 'imagenes/Mamiferos/zarigueya.png', 'La zarigüeya común, también llamado tlacuache común, raposa, rabipelado, runcho, chucha o fara es una especie de marsupial didelfimorfo de la familia Didelphidae propia del sureste de Norteamérica (sureste de México), toda América Central y norte de Suramérica.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('26', 'Zarigüeya ratón (Marmosa)', 'imagenes/Mamiferos/zarigueya_raton.png', 'La zarigüeya común, también llamado tlacuache común, raposa, rabipelado, runcho, chucha o fara es una especie de marsupial didelfimorfo de la familia Didelphidae propia del sureste de Norteamérica (sureste de México), toda América Central y norte de Suramérica.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('27', 'Zorro (Pseudalopex)', 'imagenes/Mamiferos/zorro.png', 'Lycalopex es un género de cánidos medianos o pequeños, nativos de Sudamérica, a los que se conoce de forma genérica como zorros en su área de origen. Fue descrito por Burmeister en 1854, quien en 1856 describió también el género Pseudalopex,  que es sinónimo del primero.  A pesar de ello, las especies Lycalopex culpaeus (Molina, 1782), Lycalopex griseus (Gray, 1837), Lycalopex gymnocercus (G. Fischer, 1814), Lycalopex sechurae Thomas, 1900 y Lycalopex vetulus (Lund, 1842) se podían ver escritas y encontrar como pertenecientes al género Pseudalopex, todavía a mediados de la década de 2010.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('28', 'Zorro gris (Urocyon cinereoargenteus)', 'imagenes/Mamiferos/zorro_gris.png', 'El zorro gris (Urocyon cinereoargenteus) es una especie de mamífero carnívoro de la familia Canidae distribuida por el continente americano, desde el sur de Canadá a Venezuela. En algunos lugares de Hispanoamérica se le conoce como tigrillo, ostoche o gato de monte, debido probablemente a sus largos bigotes más propios de un felino que de un cánido. Se trata de una de las dos especies actuales agrupadas dentro del género Urocyon, el cual es autóctono de Norteamérica. Algunos cánidos del género Lycalopex que habitan en el cono sur americano también son llamadas a veces zorros grises, pero no están emparentados de forma estrecha con esta especie.', 'mamiferos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('29', 'Camarón (Macrobracium americanum)', 'imagenes/Crustaceos/camaron.png', '...', 'crustaceos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('30', 'Cangrejo de agua dulce (Potamocorcinus colombiensis)', 'imagenes/Crustaceos/cangrejo_agua_dulce.png', '...', 'crustaceos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('31', 'Cangrejo ermitaño (Paguroidea)', 'imagenes/Crustaceos/cangrejo_ermitaño.png', 'Los paguroideos (Paguroidea) son una superfamilia de crustáceos decápodos, conocidos popularmente como cangrejos ermitaños o paguros. Estos crustáceos tienen en común el uso de conchas de caracol para cubrir su abdomen, que es más blando que el de otros cangrejos. Este tipo de relación interespecífica que mantiene con las conchas de los moluscos muertos se denomina tanatocresis, y es uno de los pocos animales que la realiza. Existen alrededor de 500 especies de cangrejos ermitaños alrededor del mundo, siendo la mayoría acuáticos, pero existiendo algunos terrestres. Sólo la parte delantera está cubierta por un exoesqueleto rígido. Para protegerse se refugia dentro de conchas vacías de moluscos. Su abdomen está enroscado para que pueda caber dentro de la concha; además, sus patas y pinzas le permiten bloquear la entrada. A medida que el cangrejo crece, debe cambiar de casa. Empieza por inspeccionar detenidamente con sus pinzas las conchas vacías y cuando encuentra la adecuada, se muda rápidamente. Para los cangrejos ermitaños encontrar una concha vacía es cuestión de vida o muerte, por lo que son frecuentes las luchas entre ellos cuando hay pocas disponibles.', 'crustaceos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('32', 'Cangrejo rojo de Utría (Hipolobocera utriensis)', 'imagenes/Crustaceos/camaron_rojo.png', '...', 'crustaceos');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('33', 'Basilisco de cabeza roja (Basiliscus galeritus)', 'imagenes/Serpientes/basilisco.png', 'El basilisco de cabeza roja o basilisco con casco (Basiliscus galeritus) es una especie de basilisco de tamaño medio. Es nativo del noroeste de Sudamérica. El basilico con casco habita en las selvas del oeste de Colombia y Ecuador, usualmente a altitudes menores a 1600 metros. Algunos reportes de Centro América acerca de su hábitat son incorrectos ya que se refieren realmente al Basilisco común, una especie bastante cercana al Basiliscus galeritus. El basilisco de cabeza roja fue introducido en la Isla Gorgona en el pacifco colombiano y ha puesto en peligro especies endémicas de la isla, en especial el Anolis gorgonae. Es una especie común y no es considerada amenazada.', 'serpientes');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('34', 'Boa común (Boa constrictor imperator)', 'imagenes/Serpientes/boa.png', 'La boa común (Boa constrictor imperator) conocida como mazacuata y limacoa en México, El Salvador y Guatemala (del náhuatl mazacoatl, \"culebra-venado\"), es una subespecie de la Boa constrictor. Es una especie endémica de América Central, pudiéndose también encontrar en Brasil,Venezuela,Colombia y México. Es una de las boas más pequeñas, tienen en promedio entre 1,3 m y 2,5 m de longitud; cuando crece completamente, puede alcanzar hasta 3,7 m Normalmente pesan alrededor de 6 kg y las hembras son significativamente más grandes que los machos. Su tiempo de vida salvaje es de 20 a 30 años, pero pueden exceder los 40 en cautiverio. se puede alimentar de pequeños mamíferos, como ratas, ratones y conejos, así como utilizan el mismo sistema \"constrictor\" de la anaconda y demás \"boidae\".', 'serpientes');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('35');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('36');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('37');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('38');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('39');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('40');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('41');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('42');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('43');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('44');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('45');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('46');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('47');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('48');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('49');
INSERT INTO `reservanatural`.`animal` (`idave`) VALUES ('50');

UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Crustaceos/cangrejo_rojo.png' WHERE (`idave` = '32');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '15');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '16');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '17');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '18');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '19');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '20');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '21');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '22');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '23');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '24');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '25');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '26');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '27');
UPDATE `reservanatural`.`animal` SET `tipo` = 'mamifero' WHERE (`idave` = '28');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Caimán tulisio (Caiman crocodilus)', `Imagen` = 'imagenes/Serpientes/caiman.png', `Descripcion` = 'El caimán de anteojos, cachirre, babilla, blanco, guagipal o baba (Caiman crocodilus) es una especie de reptil carnívoro que habita los diferentes tipos de cursos de agua dulce, ciénagas y pantanos en el sur de México, Centroamérica y el noroeste de América del Sur.  Fue introducido en Puerto Rico como mascota en los años 1960 y 1970, y actualmente se encuentra en todos los cuerpos de agua de la isla. Los machos llegan a medir entre 1,8 y 2,5 m de largo, y las hembras 1,4 m. Se alimentan de diferentes especies de animales: crustáceos, peces, anfibios, reptiles, aves y mamíferos grandes y pequeños. El apareamiento ocurre en la estación lluviosa. La hembra hace el nido aglomerando pequeñas cantidades de vegetación seca y tierra y pone allí de 15 a 40 huevos. La incubación dura un promedio de 13 semanas. Al nacer, las crías miden unos 20 cm.', `tipo` = 'serpientes' WHERE (`idave` = '35');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Cocodrilo aguja (Crocodylus acutus)', `Imagen` = 'imagenes/Serpientes/cocodrilo.png', `Descripcion` = 'El cocodrilo americano, también conocido como cocodrilo narigudo, cocodrilo aguja, caimán de la costa (Venezuela), caimán de aguja (Colombia) o cocodrilo de Tumbes (Perú) (Crocodylus acutus), es una especie de crocodílido que vive en Florida, algunas islas del Mar Caribe, varias zonas costeras del golfo de México, ríos de la costa caribeña de Honduras, Nicaragua, Costa Rica, Panamá, Colombia y Venezuela, y a lo largo de la costa del océano Pacífico, desde México hasta el norte de Perú. Se le suele confundir con los aligátores (Alligator), con los cuales está poco emparentado, pues estos últimos son más próximos a los caimanes, como el yacaré overo (Caiman latirostris). Las diferencias físicas entre ambos son importantes, lo que permite identificarlos sin problemas.', `tipo` = 'serpientes' WHERE (`idave` = '36');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Iguana verde (Iguana iguana)', `Imagen` = 'imagenes/Serpientes/iguana.png', `Descripcion` = 'La iguana común o iguana verde (Iguana iguana) es un gran lagarto arbóreo de América Central y de Sudamérica. Se encuentra desde México hasta el sudeste de Brasil y el Pantanal del Paraguay, así como también en islas del Caribe y, de manera asilvestrada, en Florida (Estados Unidos). Miden hasta 2 m de longitud de cabeza hasta la cola y pueden llegar a pesar más de 15 kg. Pertenece al grupo mayor y de más complicado diseño de los saurios del Nuevo Mundo, al que pertenecen la mayoría de las especies. Se incluye en la familia de los iguánidos.', `tipo` = 'serpientes' WHERE (`idave` = '37');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Serpiente bejuco (Oxybelis brevirostis)', `Imagen` = 'imagenes/Serpientes/serpiente_bejuco.png', `Descripcion` = '...', `tipo` = 'serpientes' WHERE (`idave` = '38');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Serpiente de coral', `Imagen` = 'imagenes/Serpientes/serpiente_coral.png', `Descripcion` = 'Las serpientes de coral, serpientes rabo de ají o coralillos son un grupo de serpientes venenosas de la familia Elapidae propias de zonas tropicales. Se caracterizan por sus vivos colores, entre los que predominan el amarillo, el rojo y el negro. ', `tipo` = 'serpientes' WHERE (`idave` = '39');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Tortuga bache (Cherydra serpentina)', `Imagen` = 'imagenes/Serpientes/tortuga_bache.png', `Descripcion` = '...', `tipo` = 'serpientes' WHERE (`idave` = '40');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Tortuga carey (Eretmochelys imbricata)', `Imagen` = 'imagenes/Serpientes/tortuga_carey.png', `Descripcion` = 'La tortuga carey (Eretmochelys imbricata) es una especie de tortuga marina de la familia de los quelónidos, que se halla en peligro crítico de extinción. Es la única especie del género Eretmochelys. Existen dos subespecies, Eretmochelys imbricata imbricata que se puede encontrar en el océano Atlántico y Eretmochelys imbricata bissa, localizada en la región indo-pacífica. Su aspecto es similar al de otras tortugas marinas. Tiene un cuerpo plano, un caparazón protector, y sus extremidades en forma de aletas están adaptadas para nadar en mar abierto. Se distingue fácilmente de otras tortugas marinas por su pico puntiagudo y curvo con una prominente mandíbula superior (tomium) y por los bordes en forma de sierra de su caparazón. Aunque la tortuga pasa parte de su vida en mar abierto, se la encuentra más frecuentemente en lagunas poco profundas y arrecifes de coral, donde encuentra fácilmente su presa preferida, las esponjas de mar. Algunas de las esponjas de las que se alimenta son conocidas por ser altamente tóxicas y letales para otros organismos por su alto contenido de óxido de silicio, lo que convierte a la tortuga carey en uno de los pocos animales capaces de alimentarse de organismos silíceos. También se alimentan de otros invertebrados, como tenóforos y medusas. A causa de las prácticas de pesca humanas, las poblaciones de esta especie a lo largo de todo el mundo se encuentran en serio peligro, por lo que ha sido clasificada por la Unión Internacional para la Conservación de la Naturaleza como especie en peligro crítico de extinción.1 Varios países, como China y Japón, las han cazado por su carne, considerada un manjar. Los caparazones de las carey y el material que los constituye (también llamado carey) ha sido empleado para la confección de objetos decorativos. Asimismo, se denomina carey, por extensión, al material del que se conforman los caparazones de otras tortugas marinas empleados en idéntica producción artesanal. Según el Convenio sobre el Comercio Internacional de Especies de Fauna y Flora Salvaje Amenazadas (CITES), la captura y el comercio de estas tortugas y sus productos derivados son ilegales en muchas naciones. ', `tipo` = 'serpientes' WHERE (`idave` = '41');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Tortuga golfina (Lepidochelys olivacea)', `Imagen` = 'imagenes/Serpientes/tortuga_golfina.png', `Descripcion` = 'La tortuga olivácea o golfina (Lepidochelys olivacea) es una especie de tortuga de la familia Cheloniidae; es la más pequeña de las tortugas marinas. Se distribuye por la mayor parte de los mares tropicales del mundo. Es en estas regiones donde cría. También se encuentra en mares de regiones subtropicales que usa para sus movimientos migratorios. Abunda en el Pacífico oriental; predomina una mayor concentración de ellas en Venezuela, México, Guatemala; Honduras, El Salvador, Nicaragua, Costa Rica, al sur de Panamá y Colombia. También se encuentra en Ecuador, Perú y el norte de Chile. Las tortugas golfinas son omnívoras, alimentándose de cangrejos, camarones, langostas de roca, la vegetación marina, algas, caracoles, peces y pequeños invertebrados; a veces se alimentan lapiceros en aguas poco profundas.', `tipo` = 'serpientes' WHERE (`idave` = '42');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Tortuga pintada (Trachemys scripta)', `Imagen` = 'imagenes/Serpientes/tortuga_pintada.png', `Descripcion` = 'La tortuga pintada, tortuga escurridiza o jicotea (Trachemys scripta) es una especie de tortuga de la familia Emydidae. Vive en ciénagas y otras aguas dulces. Se alimenta de diversos animales y plantas. Se distribuye por el este de Estados Unidos y nordeste de México, y ha sido introducida, debido a su popularidad como mascota, en el oriente de Asia, Australia y en Europa,1 especialmente la subespecie norteamericana Trachemys scripta elegans. Se ha prohibido la introducción de esta especie en Europa debido a que se han creado poblaciones en muchos lugares del continente por la suelta incontrolada de ejemplares que se habían adquirido como mascotas, y que han provocado daños en los ecosistemas locales, al ser una especie invasora,2 uno de los países que ha llevado a cabo esta prohibición es España.', `tipo` = 'serpientes' WHERE (`idave` = '43');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('51', 'Rana cocoi (Dendrobates histrionicus)', 'imagenes/Anfibios/rana_cocoi.png', 'La rana cocoi o rana arlequín venenosa (Oophaga histrionica) es una especie de anfibio que se encuentra en los bosquestropicales húmedos de la región del Pacífico, al occidente de Ecuador y Colombia. Su cuerpo alcanza una longitud entre 36 y 42 mm. Es una especie muy llamativa por su gran colorido, generalmente con manchas anaranjadas o también amarillas, rojas, blancas o azules, sobre negro brillante, marrón o azul. La piel es lisa y abundantemente provista de glándulas productoras de veneno. Cuando es adulta se alimentan de insectos, en especial hormigas, ácaros y otros pequeños artrópodos, ayudando a mantener el equilibrio natural. Secreta una sustancia viscosa venenosa cuando es sometida a estrés, la cual puede causar parálisis respiratoria.', 'anfibios');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('52', 'Rana flecha roja y azul (Dendrobates pumilio)', 'imagenes/Anfibios/rana_flecha.png', 'La rana flecha roja y azul (Oophaga pumilio, designada anteriormente como Dendrobates pumilio) es una especie de rana veneno de dardo, distribuida por la vertiente caribeña desde el este de Nicaragua, Costa Rica y hasta el oeste de Panamá(incluyendo algunas islas del archipiélago de Bocas del Toro). Su coloración aposemática es muy llamativa, lo cual advierte a los posibles depredadores que dicha rana contiene un potente veneno neurotóxico (especialmente pumiliotoxinas) en la piel. En 30 años de investigación se han registrado en esta especie más de 230 alcaloides de 21 diferentes clases estructurales.3 El veneno de estas ranas es tomado de los insectos que consume, principalmente de hormigas de los géneros Brachymyrmex y Paratrechina4 y garrapatas de suelo de la familia Oribatidae.3 Si se le alimenta en cautiverio sólo con moscas de la fruta (Drosophila melanogaster) dejan de portar veneno en la piel (John Daly comunicación personal).', 'anfibios');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('53', 'Sapo (Bufo bufo)', 'imagenes/Anfibios/sapo.png', 'El sapo común (Bufo bufo) o sapo europeo es una especie de anfibio anuro de la familia Bufonidae muy habitual en toda clase de hábitats europeos, sobre todo en aguas estancadas: balsas de riego, albercas, etc, al ser más resistente a las aguas insalubres que otras especies de anfibios durante la fase de renacuajo.  Se distribuye por toda Europa salvo Irlanda, Islandia y algunas islas mediterráneas, además de Asia noroccidental y pequeñas partes del noreste africano. Es uno de los anfibios más conocidos, dada su distribución y requerimientos ecológicos laxos. Es una especie de un grupo de ellas estrechamente relacionadas, que descienden de una línea ancestral común y que forman un complejo de especies. El sapo es un animal poco visible, ya que por lo general se esconde durante el día. Se activa al atardecer y caza de noche los invertebrados de que se alimenta principalmente. Se mueve con un paso lento y torpe o a saltos cortos; tiene la piel de color marrón grisáceo, cubierta de protuberancias parecidas a verrugas. Aunque los sapos son generalmente animales solitarios, en la época de reproducción un gran número de ellos converge en ciertos estanques de cría, donde los machos compiten por aparearse con las hembras. Los huevos, en forma de cadenas gelatinosas, son depositados en el agua y de ellos eclosionan los renacuajos. Después de varios meses de crecimiento y desarrollo, les brotan los miembros y metamorfosean a pequeños sapos; éstos salen del agua y en adelante serán mucho más terrestres que acuáticos. El sapo común parece estar en declive en ciertas regiones. Está amenazado por la pérdida de hábitat, sobre todo por el drenaje de sus lugares de reproducción y el tráfico rodado que interfiere en sus migraciones anuales. Tradicionalmente, en la cultura popular y la literatura se ha asociado con, por ejemplo, la brujería o el Demonio y en general, ha estado connotado negativamente.', 'anfibios');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Arácnidos (Arachnida)', `Imagen` = 'imagenes/Anfibios/aracnidos.png', `Descripcion` = 'Los arácnidos (Arachnida, del griego -αράχνη -aráchne, \"araña\" e -ιδες -ides, \"perteneciente a un grupo\") son una clase de artrópodos quelicerados de la que han sido descritas más de 102.000 especies. Incluye formas tan conocidas como las arañas, las garrapatas y otros ácaros, o los escorpiones.', `tipo` = 'anfibios' WHERE (`idave` = '44');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Mariposa (Lepidoptera)', `Imagen` = 'imagenes/Anfibios/mariposa.png', `Descripcion` = 'Los lepidópteros son un orden de insectos holometábolos, casi siempre voladores, conocidos comúnmente como mariposas; las más conocidas son las mariposas diurnas, pero la mayoría de las especies son nocturnas (polillas, esfinges, pavones, etc.) y pasan muy inadvertidas. Sus larvas se conocen como orugas y se alimentan típicamente de materia vegetal, pudiendo ser algunas especies plagas importantes para la agricultura. Muchas especies cumplen el rol de polinizadores de plantas y cultivos. Este taxón representa el segundo orden con más especies entre los insectos (siendo superado solamente por el orden Coleoptera); de hecho, cuenta con más de 165 000 especies1 clasificadas en 127 familias y 46 superfamilias.  La mariposa diurna más grande que existe es la Ornithoptera alexandrae hembra, que puede llegar a tener 31 cm de envergadura (el macho es un poco más pequeño), vive al sudeste de Nueva Guinea.', `tipo` = 'anfibios' WHERE (`idave` = '45');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Mojarra', `Imagen` = 'imagenes/Anfibios/mojarra.png', `Descripcion` = '...', `tipo` = 'anfibios' WHERE (`idave` = '46');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Pez cofre (Lactoria cornuta)', `Imagen` = 'imagenes/Anfibios/pez.png', `Descripcion` = 'El pez cofre cornudo, pez vaca o también llamado anteriormente pez toro (Lactoria cornuta), es una variedad de pez cofre, reconocible por los largos cuernos que sobresalen al frente de su cabeza, como los de una vaca o un toro. Estos peces miden unos 10 cm de largo, aunque pueden llegar hasta los 51 centímetros. Los adultos son generalmente solitarios y territoriales, viviendo sobre arena o escombros hasta una profundidad de 50m. Son omnívoros: se alimentan de algas bentónicas, algunos microorganismos, y los foraminíferos que filtran de los sedimentos, corales, esponjas, poliquetos de la arena, moluscos, crustáceos pequeños, y peces pequeños, siendo capaz de alimentarse de invertebrados bentónicos al soplar chorros de agua en el sustrato arenoso.', `tipo` = 'anfibios' WHERE (`idave` = '47');
INSERT INTO `reservanatural`.`animal` (`tipo`) VALUES ('');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Rana del Alto del Buey (Dendrobates altobueyensis). (endémica)', `Imagen` = 'imagenes/Anfibios/rana_buey.png', `Descripcion` = 'Andinobates altobueyensis es una especie de anfibio de la familia Dendrobatidae que es endémica de Colombia. Andinobates altobueyensis habita en los suelos y bromelias del bosque húmedo premontano de la región Pacífica colombiana.2 Sus huevos son probablemente colocados en hojas, una vez eclosionado el renacuajo, es llevado hasta una bromelia por el adulto, aunque esto aún es incierto.', `tipo` = 'anfibios' WHERE (`idave` = '50');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Rana arlequín (Atelopus spurrelli). (endémica)', `Imagen` = 'imagenes/Anfibios/rana_alerquin.png', `Descripcion` = 'Atelopus spurrelli es una especie de anfibios de la familia Bufonidae. Es endémica de Colombia. Su hábitat natural incluye bosques tropicales o subtropicales secos y a baja altitud y ríos. Está amenazada de extinción por la pérdida de su hábitat natural.', `tipo` = 'anfibios' WHERE (`idave` = '49');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Rana arborícola (Eleutherodactylus)', `Imagen` = 'imagenes/Anfibios/rana_aboricola.png', `Descripcion` = 'Eleutherodactylus es un género diverso de anfibios anuros de la familia Eleutherodactylidae.1 Los miembros de este género se encuentran en el sur del estado de Texas en los Estados Unidos, México, Belice, Guatemala y las Indias Occidentales. El género Eleutherodactylus solía tener más de 800 especies, pero se consideraba como un grupo artificial por la pobre información disponible. El género fue separado usando datos de ADN mitocondrial y ahora muchos de ellos están en las familias Craugastoridaeo Brachycephalidae. Una de las especies más conocida es el coquí común (Eleutherodactylus coqui), el cual es el símbolo nacional de Puerto Rico, y notable invasor en Hawái. Dos especies de este género, E. limbatus y E. iberia, están entre los tetrápodos más pequeños del mundo, midiendo apenas 8,5 mm de longitud, algo más que Paedophryne amauensis que ostenta el récord.', `tipo` = 'anfibios' WHERE (`idave` = '48');

UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Serpientes/serpiente.png' WHERE (`idave` = '38');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Anfibios/pez_cofre.png' WHERE (`idave` = '47');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Anfibios/rana_arboricola.png' WHERE (`idave` = '48');
UPDATE `reservanatural`.`animal` SET `Imagen` = 'imagenes/Anfibios/rana_arlequin.png' WHERE (`idave` = '49');
UPDATE `reservanatural`.`animal` SET `Nombre` = 'Armadillo (Dasypodidae)', `Imagen` = 'imagenes/Mamiferos/armadillo.png' WHERE (`idave` = '15');



CREATE TABLE `reservanatural`.`flora` (
  `idflora` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NULL,
  `Imagen` VARCHAR(500) NULL,
  `Descripcion` VARCHAR(50000) NULL,
  PRIMARY KEY (`idflora`));

INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('1', 'Abarco', 'imagenes/Flora/abarco.jpg', 'alcanza en promedio 25 m de altura. Tiene hojas simples, alternas, con margen aserrado y ápice acuminado, son elípticas de hasta 12 cm de longitud por 5 cm de ancho. Fruto comestible, oblongo de color marrón, de 8 a 9 cm de largo.Una de las especies nativas más promisorias de Colombia, dada su excelente dureza y una similitud sorprendente en apariencia con algunas valiosas especies africanas. Pese a que en Colombia no existen hectáreas representativas de bosque natural, ni plantaciones con fines de explotación comercial, este es considerado como un tesoro forestal.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('2', 'Dialium', 'imagenes/Flora/Dialium.jpg', 'Son árboles, que alcanza un tamaño de hasta 35 m de alto, inermes, fúlcreos en la base, savia tornándose roja brillante cuando es expuesta. Hojas 1-pinnadas; folíolos 5–7 (–9), opuestos o alternos, ovados a lanceolados, 3–10 cm de largo y 1.5–4 cm de ancho, ápice agudo a acuminado, base redondeada a cuneada, membranáceos a subcoriáceos, glabros, reticulados, peciólulos 2–3 mm de largo, acanalados o aplanados adaxialmente.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('3', 'Parkia pendula', 'imagenes/Flora/Parkia pendula.jpg', 'Es un árbol muy grande que puede alcanzar de 15 hasta 50 metros de altura, alcanzando normalmente el dosel forestal. Posee raíces tablares de hasta 2,5 metros de altura. Su tronco es erecto y cilíndrico, libre de ramas hasta gran altura y puede medir hasta 1,20 metros de diámetro. Sus corteza es de color grisáceo-blancuzco a pardo-rojizo que exfolia en placas grandes de forma variable con numerosas lenticelas. Las ramas son blancuzcas y muy extendidas.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('4', 'V. sebifera', 'imagenes/Flora/Virola_sebifera.jpg', 'es un árbol alto y delgado que crece entre 5-30 m (16-98 pies) de altura. [1] Las hojas son simples y crecen hasta 30 cm (12 in) de largo. Las flores pequeñas son de un solo sexo y se encuentran en panículas . El fruto es rojizo, de forma ovalada, y tiene unos 10-15 mm (0.39-0.59 in) de largo y unos 11 mm (0.43 in) de diámetro. [1] Los árboles de Virola individuales , que incluyen 40 a 60 especies, son difíciles de diferenciar entre sí.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('5', 'Brassavola', 'imagenes/Flora/Brassavola_nodosa.jpg', 'Estas especies tienen flores de color blanco en racimos que pueden ser erectos o péndulos.La mayoría son epifitas, pero unas pocas son litófitas. Están muy próximas a Cattleya con las que solo tienen de diferencia el número de polinia que en este género suelen ser a veces 12 y otras 8 que son desiguales. Los tallos son normalmente cortos.Los pseudobulbos de unos 6 a 30 cm de longitud, son estrechos con forma de lapiceros, y están claramente separados. Cada pseudobulbo desarrolla una hoja cerea y aspecto de cuero de unos 20 cm de longitud.La inflorescencia es una sola o en racimo de unas pocas flores con unos sépalos y pétalos largos y estrechos. Tienen la base del labelo que abraza una parte de la columna que transporta de 12 a 8 polinias desiguales.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('6', 'Bromelia', 'imagenes/Flora/Bromelias.jpg', 'Es un género tropical americano de plantas de la familia Bromeliceae. Son plantas de hábitos terrestres, herbáceas, litófitas, que crecen sobre piedras o bien son epífitas que se desarrollan sobre árboles, cactus, etc. acaulescentes a cortamente caulescentes, rizomatosas o estoloníferas; plantas hermafroditas. Hojas arrosetadas y usualmente sin tallo, gruesamente armadas. Inflorescencia sésil o escapífera, pinnada o fasciculado compuesta (simple), sublaxamente alargada a subcapitada; sépalos libres o rara vez connados; pétalos libres, carnosos; estambres connados; ovario ínfero o súpero. Fruto una baya; semillas sin apéndices.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('7', 'Caimito', 'imagenes/Flora/caimito.jpg', 'es un árbol tropical de la familia Sapotaceae, originario de las áreas de baja elevación de América Central y del Caribe. Crece rápidamente y puede llegar a una altura de veinte metros.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('8', 'Caoba', 'imagenes/Flora/caoba.jpg', 'Ewietenia macrophylla es una especie botánica de árboles originaria de la zona intertropical americana perteneciente a la familiade las Meliaceae. Su nombre común principal es el de caoba de Honduras o caoba de hoja grande.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('9', 'Ceiba pentandra', 'imagenes/Flora/ceiba_pentanbra.jpg', 'El árbol alcanza 60 a 70 metros de altura, con un tronco grueso que puede llegar a medir más de 3 m de diámetro, con raíces tabulares. El tronco y muchas de sus ramas mayores están densamente pobladas de espinas largas y robustas. Las hojas están divididas en 5 a 9 folíolos más pequeños, cada hoja sobrepasa los 20 cm. Los árboles adultos producen varios cientos de frutos, cápsulas dehiscentes de unos 15 cm (a veces mal llamadas vainas, que es otro fruto diferente). Las cápsulas contienen semillas que se encuentran rodeadas por una fibra amarillenta de aspecto algodonoso, que es una mezcla de lignina y de celulosa.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('10', 'Fresno', 'imagenes/Flora/fresno.jpg', 'Son arbustos a árboles grandes; plantas dioicas o poligamodioicas. Hojas alternas, imparipinnadas, raramente paripinnadas, siempreverdes; folíolos opuestos o a veces subopuestos, peciolulados, márgenes enteros. Inflorescencias subterminales, paniculadas, las últimas ramas a veces espigadas; flores pediceladas o sésiles, 5-meras, imbricadas, corola amarillo verdosa, amarilla o color crema; estambres (8–) 10, en 2 series (a veces marcadamente) desiguales, filamentos lineares a subulados; disco intrastaminal 5–10-lobado; ovario 1-locular, densamente pubescente, el único óvulo apical o subapicalmente suspendido, estilos (4–) 5, libres, estigmas capitados.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('11', 'Helechos', 'imagenes/Flora/helechos.jpg', 'son plantas vasculares sin semilla (pteridofitas), cuyas características morfológicas más sobresalientes son sus hojas grandes (\"megafilos\" o \"frondes\"), usualmente pinadas y con prefoliación circinada. Tradicionalmente ha agrupado a 3 gruposː los helechos leptosporangiados (Polypodiidae), maratiales y ofioglosales, sin embargo, los análisis genéticos modernos encontraron que los ofioglosales están relacionados con los psilotales, los cuales históricamente se clasificaron aparte al considerárseles primitivos, agrupándose ahora juntos en un solo taxón llamado Ophioglossidae o Psilotopsida.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('12', 'Nectandra', 'imagenes/Flora/Nectandra.jpg', 'Son árboles o arbustos; hermafroditas. Las hojas alternas, enteras, glabras o con pubescencia variada, pinnatinervias. Las inflorescencias axilares o pseudoterminales, paniculadas, las últimas divisiones cimosas, mayormente algo pubescentes, las floresson pequeñas, raramente más de 1 cm de diámetro, blancas o verdosas; tépalos iguales. El fruto es una baya asentada sobre una cúpula poco profunda.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('13', 'Mangle', 'imagenes/Flora/mangle.jpg', 'es un arbusto o árbol leñoso, perteneciente a las rizoforáceas. Tiene frutos, de tres a cuatro metros de altura, aunque a veces alcanza unos 15 metros o más. Sus ramas largas y extendidas dan vástagos que descienden hasta tocar el suelo y arraigar en él. Tiene hojas pecioladas, opuestas, enteras, elípticas, obtusas y gruesas; flores axilares de cuatro pétalos amarillentos; fruto seco de corteza coriácea, pequeño y casi redondo y muchas raíces externas en parte. Los mangles forman ecosistemas, llamados manglares.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('14', 'Mangle negro', 'imagenes/Flora/mangle_negro.jpg', 'Es un árbol o arbusto que alcanza un tamaño de 3–10 m de alto. Tiene hojas angostas, elíptico-oblongas, de 6,5–10 cm de largo y 1,5–3 cm de ancho, con ápice agudo (agudo-redondeado), y base cuneada. Inflorescencia en forma de panícula de espigas 1 (2)-compuesta, de 9 cm de largo y 2–5 cm de ancho, flores agrupadas en los extremos, bráctea floral ovada, de 2,5–3 mm de largo, bractéolas lanceoladas, de 2,5–4 mm de largo; cáliz de 3,5–4,5 mm de largo; corola de 4,5–8 mm de largo; estambres con anteras exertas, filamentos de 2,5–4 mm de largo, todos similares y filiformes. Fruto ovado-oblicuo, apiculado, de 1,5–2 cm de largo y 1–1,5 cm de ancho, escasamente seríceo.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('15', 'Mangle blanco', 'imagenes/Flora/mangle_blanco.jpg', 'Son arbustos o árboles, que alcanzan un tamaño de hasta 15 m de alto, con raíces zancudas y frecuentemente con neumatóforos; plantas mayormente hermafroditas pero a menudo andromonoicas y a veces dioicas.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('16', 'Mangle piñuelo', 'imagenes/Flora/mangle_piñuelo.jpg', 'Son árboles generalmente siempreverdes; plantas hermafroditas. Hojas alternas, simples, nervadura pinnada, nervios secundarios inconspicuos; sin estípulas. Flores solitarias, axilares (de apariencia terminal), regulares, cada una abrazada por 2 bractéolas; sépalos 5, libres, imbricados, caducos; pétalos 5, libres, imbricados; estambres 5, libres, alternos con los pétalos, adpresos en las ranuras del ovario, anteras abriéndose longitudinalmente, conectivo prolongado; ovario súpero, con 2 carpelos unidos, 2-locular, placentación axial, 1 óvulo por lóculo (uno de ellos vacío), un estilo con estigma punctiforme. Fruto seco y coriáceo, indehiscente con 1 lóculo y 1 semilla.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('17', 'Mangle rojo', 'imagenes/Flora/mangle_rojo.jpg', 'Es un árbol que alcanza un tamaño de hasta 20 m de alto. Tiene las hojas elípticas, de 11–15 cm de largo y 4–7 cm de ancho, el ápice agudo, la base cuneada, glabras, envés con puntos negros. La inflorescencia de 5–12 cm de largo, 3–5 veces ramificada, con numerosas flores, pedúnculo de 2–7 cm de largo, con brácteas gruesas, bífidas; pedicelos 3–11 mm de largo, flores 1 cm de largo; estambres 8; yema floral ovada o ligeramente elíptica, ápice agudo. Fruto ovado-lanceolado, 4 cm de largo y 1.5 cm de ancho, radícula 11–25 cm de largo.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('18', 'Miconia', 'imagenes/Flora/Miconia.jpg', 'Arbustos o árboles hasta 20 m de alto con un diámetro hasta de 50 cm, tronco derecho, a veces con chupones, copa redondeada y ramas ascendentes. La corteza externa es escamosa que se desprende en tiras largas irregulares de color gris pardusco o amarillenta ligeramente rojiza. Las ramas jóvenes, pecíolos, envés, inflorescencias e hipanto cubierto por un denso tomento estrellado pardo claro, los entrenudos distales marcadamente aplanados y con 2 bordes. ');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('19', 'Mora oleifera', 'imagenes/Flora/mora_oleifera.jpg', 'Son árboles, que alcanzan un tamaño de hasta 45 m de alto, inermes, con grandes contrafuertes, corteza café-rojiza. Hojas 1-pinnadas; folíolos 2 o 3 pares, elípticos a elíptico-oblongos, 8–18 cm de largo y 4–7 cm de ancho, ápice agudo-acuminado, base redondeada a obtusa, glabros, coriáceos o subcoriáceos, reticulados, no punteado-glandulares, peciólulos 2–3 mm de largo, acanalados a planos; raquis plano en el lado abaxial, estípulas caducas. Inflorescencias panículas terminales o subterminales de espigas, 7–10 cm de largo, glabras, con numerosas flores pequeñas, blancas, sésiles; cáliz campanulado con un tubo corto, lobos 5, 3–4 mm de largo, apicalmente redondeados, imbricados, ciliados; pétalos 5, oblongos, imbricados, 5–6 mm de largo y 2.5–3 mm de ancho; estambres 5, libres, distalmente lanosos, alternando con 5 estaminodios apicalmente dilatados; ovario subsésil, lanoso, óvulos 2 o 3, estilo corto, glabro, estigma terminal, pequeño. Fruto oblongo, hasta 25 cm de largo y 10–13 cm de ancho, valvas leñosas, lisas a subverrugosas, dehiscente; semilla 1 (2), reniforme, hasta 18 cm de largo y 12 cm de ancho, testa delgada.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('20', 'Palma areacáceas', 'imagenes/Flora/Palma_arecáceas.jpg', 'es una familia de plantas monocotiledóneas, la única familia del orden Arecales (sinónimo Principales). Normalmente se las conoce como palmeras o palmas. Los individuos de esta importante familia son fáciles de reconocer visualmente, aunque puede haber confusión con especies de las familias Cycadaceae y Zamiaceae debido a las similitudes morfológicas. Son plantas leñosas (pero sin crecimiento secundario del tronco, solo primario). A pesar de ser monocotiledóneas muchas de ellas son arborescentes, con grandes hojas en corona al final del tallo, generalmente pinnadas (pinnatisectas) o palmadas (palmatisectas). Sus flores poseen 3 sépalos y 3 pétalos, y se disponen en inflorescencias provistas de una o varias espatas. El fruto es carnoso: una baya o una drupa. Están ampliamente distribuidas en regiones tropicales a templadas, pero principalmente en regiones cálidas.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('21', 'Palma de seje', 'imagenes/Flora/Palma_seje.jpg', 'Es una palma abundante en zonas húmedas y pluviales a menos de 1000 msnm al noroccidente de Sudamérica desde Panamá hasta el sur de América tropical. Se distribuye por Panamá, Venezuela, Colombia, Bolivia, Ecuador y Perú.2 Entre otros lugares, es autóctona del Municipio Cedeño (Bolívar), Estado Bolívar, Venezuela, cuyo fruto forma parte de la tradición culinaria de la regiones  .Se caracteriza por un estípite (tallo) solitario erecto, de 10 a 25 m de altura y 20 a 30 cm de diámetro, liso, conspicuamente anillado. Tiene de 10 a 16 hojas terminales, penduladas hacia los lados, con peciolo de 1 a 50 cm y raquis de 3 a 7 m de longitud; ápice acuminado, limbo pinnado, pinnas alternas de hasta 2 m de largo y 15 cm de ancho, aproximadamente 100 a cada lado, colocadas en un mismo plano.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('22', 'Palma de asaí', 'imagenes/Flora/palma_asaí.jpg', 'es una palmera nativa del norte de Sudamérica, apreciada por las propiedades nutritivas de su fruto. También se conoce con el nombre de palma manaca.');


CREATE TABLE `reservanatural`.`contactenos` (
  `idcontactenos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontactenos`));
  
  INSERT INTO `reservanatural`.`contactenos` (`idcontactenos`, `Nombre`, `Telefono`, `Correo`) VALUES ('1', 'Carlos Taborda', '3136545076', 'carlitos123@gmail.com');
  INSERT INTO `reservanatural`.`contactenos` (`idcontactenos`, `Nombre`, `Telefono`, `Correo`) VALUES ('2', 'Gloria Zapata', '12315232', 'gloria2352@gmal.com');
  INSERT INTO `reservanatural`.`contactenos` (`idcontactenos`, `Nombre`, `Telefono`, `Correo`) VALUES ('3', 'Reserva De Utria', '5808266', 'reservanaturaldeutria1@gmail.com');

