CREATE DATABASE RESERVANATURAL;

CREATE TABLE `reservanatural`.`animal` (
  `idave` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Imagen` VARCHAR(200) NULL,
  `Descripcion` VARCHAR(300) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idave`));

ALTER TABLE `reservanatural`.`animal` 
CHANGE COLUMN `Descripcion` `Descripcion` VARCHAR(50000) NULL DEFAULT NULL ;

INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('1', 'Águila harpía (Harpia harpyja)', 'imagenes/Aves/aguila.png', 'Es una especie de ave accipitriforme de la familia Accipitridae que vive en la zona neotropical. Es el águila más grande del Hemisferio Occidental y del Hemisferio Austral, y la única especie del género Harpia. Su hábitat es el bosque lluvioso. No se reconocen subespecies. s una especie de ave accipitriforme de la familia Accipitridae que vive en la zona neotropical. Es el águila más grande del Hemisferio Occidental y del Hemisferio Austral, y la única especie del género Harpia. ', 'ave');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('2', 'Colibrí (Trochilinae)', 'imagenes/Aves/colibri.png', 'Los troquilinos (Trochilinae) son una subfamilia de aves apodiformes de la familia Trochilidae, conocidas comúnmente como picaflores, colibríes, quindes, tucusitos, chupamirtos, chuparrosas, huitzitzilin (idioma náhuatl), mainumby (idioma guaraní) o guanumby. Conjuntamente con las ermitas, que pertenecen a la subfamilia Phaethornithinae, conforman la familia Trochilidae que, en la sistemática de Charles Sibley, se clasifica en un orden propio: Trochiliformes, independiente de los vencejos del orden Apodiformes. La subfamilia Trochilinae incluye más de 100 géneros que comprenden un total de 330 a 340 especies. Estos pájaros son originarios del continente americano. Antaño se los mató por miles a fin de decorar los sombreros femeninos,1​ lo que posiblemente llevó al exterminio de varias especies.  Los colibríes están entre los pájaros más pequeños que existen. La especie de tamaño más reducido es el colibrí zunzuncito o elfo de las abejas (Mellisuga helenae), que con su pico y cola mide apenas unos 5,5 centímetros, exclusivo de Cuba.3​ La especie más grande, el llamado colibrí gigante (Patagona gigas), mide unos 25 cm. La mayoría de los colibríes presenta un plumaje muy colorido, generalmente de color verde metálico. El cuello de los machos es frecuentemente rojo brillante, azul o verde esmeralda. Una característica especial de los colibríes es el pico, que diverge casi siempre de especie en especie. El colibrí pico espada (Ensifera ensifera), por ejemplo, tiene un pico casi tan largo como el cuerpo, de unos 10 cm de longitud.', 'ave');
UPDATE `reservanatural`.`animal` SET `Descripcion`='Es una especie de ave accipitriforme de la familia Accipitridae que vive en la zona neotropical. Es el águila más grande del Hemisferio Occidental y del Hemisferio Austral, y la única especie del género Harpia. Su hábitat es el bosque lluvioso. No se reconocen subespecies. s una especie de ave accipitriforme de la familia Accipitridae que vive en la zona neotropical. Es el águila más grande del Hemisferio Occidental y del Hemisferio Austral, y la única especie del género Harpia. Su hábitat es el bosque lluvioso. ' WHERE `idave`='1';
UPDATE `reservanatural`.`animal` SET `Descripcion`='Los troquilinos (Trochilinae) son una subfamilia de aves apodiformes de la familia Trochilidae, conocidas comúnmente como picaflores, colibríes, quindes, tucusitos, chupamirtos, chuparrosas, huitzitzilin (idioma náhuatl), mainumby (idioma guaraní) o guanumby. Conjuntamente con las ermitas, que pertenecen a la subfamilia Phaethornithinae, conforman la familia Trochilidae que, en la sistemática de Charles Sibley, se clasifica en un orden propio: Trochiliformes, independiente de los vencejos del orden Apodiformes. La subfamilia Trochilinae incluye más de 100 géneros que comprenden un total de 330 a 340 especies. Estos pájaros son originarios del continente americano. Antaño se los mató por miles a fin de decorar los sombreros femeninos,1​ lo que posiblemente llevó al exterminio de varias especies.  Los colibríes están entre los pájaros más pequeños que existen. La especie de tamaño más reducido es el colibrí zunzuncito o elfo de las abejas (Mellisuga helenae), que con su pico y cola mide apenas unos 5,5 centímetros, exclusivo de Cuba.3​ La especie más grande, el llamado colibrí gigante (Patagona gigas), mide unos 25 cm. La mayoría de los colibríes presenta un plumaje muy colorido, generalmente de color verde metálico. El cuello de los machos es frecuentemente rojo brillante, azul o verde esmeralda. Una característica especial de los colibríes es el pico, que diverge casi siempre de especie en especie. El colibrí pico espada (Ensifera ensifera), por ejemplo, tiene un pico casi tan largo como el cuerpo, de unos 10 cm de longitud.' WHERE `idave`='2';
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('3', 'Garza mora (Ardea cocoi)', 'imagenes/Aves/garza_mora.png', 'La garza cuca o garza mora (Ardea cocoi) es una especie de ave perteneciente al clado Ardeidae2​3​ propia de Centro y Sudamérica.', 'ave');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('4', 'Mirlo (Turdus fuscater)', 'imagenes/Aves/mirlo.png', 'La paraulata morera, mirla patinaranja, o mirlo (Turdus fuscater) es una especie de ave paseriforme sudamericana de la familia del género Turdus. Puebla zonas boscosas y de matorral de Venezuela, Colombia, Ecuador, Perú, Bolivia.', 'ave');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('5', 'Pelícano pardo (Pelecanus occidentalis)', 'imagenes/Aves/pelicano.png', 'El pelícano pardo (Pelecanus occidentalis) es una especie de ave pelecaniforme de la familia Pelecanidae que se encuentra en América desde el sur de los Estados Unidos (es el ave símbolo de Luisiana) hasta la Amazonía.', 'ave');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('6', 'Trepatroncos (Dendrocolaptidae)', 'imagenes/Aves/trepatroncos.png', 'Son aves parduzcas o rojizas, que se alimentan principalmente de insectos cazados en los troncos de los árboles. Son pájaros de bosque que anidan en agujeros o hendiduras; ponen 2 o 3 huevos blancos que incuban durante unos quince días. Siguen las colonias de hormigas que salen a recolectar, esperando que los insectos se muevan y los cazan. Se ha calculado que estos pájaros le roban aproximadamente 200 insectos grandes a una colonia de hormigas por día; lo que equivale al 15% de los requisitos de comida diarios de una colonia de hormigas legionarias.', 'ave');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('7', 'Tucán (Ramphastidae)', 'imagenes/Aves/tucan.png', 'Los ranfástidos (Ramphastidae), conocidos comúnmente como tucanes, diotedé o diostedé. Esta familia de aves ranfástidas del orden de los piciformes es muy amplia ya que alberga seis géneros y cuarenta y dos especies diferentes de tucanes. Se caracterizan por poseer un pico muy desarrollado y de vivos colores. Miden entre 18 y 65 cm, siendo el tucán toco (Ramphastos toco) el de mayor tamaño. Están ampliamente distribuido por el continente americano, desde México hasta Argentina y Colombia. Algunas especies prefieren selvas húmedas tropicales de baja altitud, mientras que otras habitan en bosques más templados en cordilleras, a altitudes hasta los 3000 msnm. El nombre de este grupo de aves procede del guaraní: tupí tucana.', 'ave');
INSERT INTO `reservanatural`.`animal` (`tipo`) VALUES ('');

UPDATE `reservanatural`.`animal` SET `Nombre`='Lophogorgia alba', `Imagen`='imagenes/Corales/Lophogorgia_alba.png', `Descripcion`='...', `tipo`='corales' WHERE `idave`='8';
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('9', 'Pocillopora damicornis', 'imagenes/Corales/Pocillopora_damicornisp.png', '...', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('10', 'Psammacora stellata', 'imagenes/Corales/Psammacora_stellata.png', '...', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('11', 'Porites paramensis', 'imagenes/Corales/Porites paramensis.png', '...', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('12', 'Pavona gigantea', 'imagenes/Corales/Pavona gigantea.png', '...', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('13', 'Pavona clavus', 'imagenes/Corales/Pavona clavus.png', 'Pavona clavus es una especie de coral de la familia Agariciidae, y pertenece al grupo de los corales duros, orden Scleractinia. Es coral hermatípico, por lo que, tras la muerte del coral, su esqueleto contribuye a la generación de nuevos arrecifes en la naturaleza. Es una especie, que por su forma de crecimiento, confiere refugio y protección a invertebrados marinos y peces. Al tiempo, que juega un importante papel dando soporte a la base de muchos arrecifes.', 'corales');
INSERT INTO `reservanatural`.`animal` (`idave`, `Nombre`, `Imagen`, `Descripcion`, `tipo`) VALUES ('14', 'Pavona varians', 'imagenes/Corales/Pavona varians.png', '...', 'corales');


CREATE TABLE `reservanatural`.`flora` (
  `idflora` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NULL,
  `Imagen` VARCHAR(500) NULL,
  `Descripcion` VARCHAR(50000) NULL,
  PRIMARY KEY (`idflora`));

INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('1', 'Abarco', 'imagenes/Flora/abarco.jpg', 'alcanza en promedio 25 m de altura. Tiene hojas simples, alternas, con margen aserrado y ápice acuminado, son elípticas de hasta 12 cm de longitud por 5 cm de ancho. Fruto comestible, oblongo de color marrón, de 8 a 9 cm de largo.Una de las especies nativas más promisorias de Colombia, dada su excelente dureza y una similitud sorprendente en apariencia con algunas valiosas especies africanas. Pese a que en Colombia no existen hectáreas representativas de bosque natural, ni plantaciones con fines de explotación comercial, este es considerado como un tesoro forestal.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('2', 'Dialium', 'imagenes/Flora/Dialium.jpg', 'Son árboles, que alcanza un tamaño de hasta 35 m de alto, inermes, fúlcreos en la base, savia tornándose roja brillante cuando es expuesta. Hojas 1-pinnadas; folíolos 5–7 (–9), opuestos o alternos, ovados a lanceolados, 3–10 cm de largo y 1.5–4 cm de ancho, ápice agudo a acuminado, base redondeada a cuneada, membranáceos a subcoriáceos, glabros, reticulados, peciólulos 2–3 mm de largo, acanalados o aplanados adaxialmente.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('3', 'Parkia pendula', 'imagenes/Flora/Parkia pendula.jpg', 'Es un árbol muy grande que puede alcanzar de 15 hasta 50 metros de altura, alcanzando normalmente el dosel forestal. Posee raíces tablares de hasta 2,5 metros de altura. Su tronco es erecto y cilíndrico, libre de ramas hasta gran altura y puede medir hasta 1,20 metros de diámetro. Sus corteza es de color grisáceo-blancuzco a pardo-rojizo que exfolia en placas grandes de forma variable con numerosas lenticelas. Las ramas son blancuzcas y muy extendidas.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('4', 'V. sebifera', 'imagenes/Flora/Virola_sebifera.jpg', 'es un árbol alto y delgado que crece entre 5-30 m (16-98 pies) de altura. [1] Las hojas son simples y crecen hasta 30 cm (12 in) de largo. Las flores pequeñas son de un solo sexo y se encuentran en panículas . El fruto es rojizo, de forma ovalada, y tiene unos 10-15 mm (0.39-0.59 in) de largo y unos 11 mm (0.43 in) de diámetro. [1] Los árboles de Virola individuales , que incluyen 40 a 60 especies, son difíciles de diferenciar entre sí.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('5', 'Brassavola', 'imagenes/Flora/Brassavola_nodosa.jpg', 'Estas especies tienen flores de color blanco en racimos que pueden ser erectos o péndulos.La mayoría son epifitas, pero unas pocas son litófitas. Están muy próximas a Cattleya con las que solo tienen de diferencia el número de polinia que en este género suelen ser a veces 12 y otras 8 que son desiguales. Los tallos son normalmente cortos.Los pseudobulbos de unos 6 a 30 cm de longitud, son estrechos con forma de lapiceros, y están claramente separados. Cada pseudobulbo desarrolla una hoja cerea y aspecto de cuero de unos 20 cm de longitud.La inflorescencia es una sola o en racimo de unas pocas flores con unos sépalos y pétalos largos y estrechos. Tienen la base del labelo que abraza una parte de la columna que transporta de 12 a 8 polinias desiguales.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('6', 'Bromelia', 'imagenes/Flora/Bromelias.jpg', 'Es un género tropical americano de plantas de la familia Bromeliceae. Son plantas de hábitos terrestres, herbáceas, litófitas, que crecen sobre piedras o bien son epífitas que se desarrollan sobre árboles, cactus, etc. acaulescentes a cortamente caulescentes, rizomatosas o estoloníferas; plantas hermafroditas. Hojas arrosetadas y usualmente sin tallo, gruesamente armadas. Inflorescencia sésil o escapífera, pinnada o fasciculado compuesta (simple), sublaxamente alargada a subcapitada; sépalos libres o rara vez connados; pétalos libres, carnosos; estambres connados; ovario ínfero o súpero. Fruto una baya; semillas sin apéndices.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('7', 'Caimito', 'imagenes/Flora/caimito.jpg', 'es un árbol tropical de la familia Sapotaceae, originario de las áreas de baja elevación de América Central y del Caribe. Crece rápidamente y puede llegar a una altura de veinte metros.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('8', 'Caoba', 'imagenes/Flora/caoba.jpg', 'Ewietenia macrophylla es una especie botánica de árboles originaria de la zona intertropical americana perteneciente a la familiade las Meliaceae. Su nombre común principal es el de caoba de Honduras o caoba de hoja grande.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('9', 'Ceiba pentandra', 'imagenes/Flora/ceiba_pentanbra.jpg', 'El árbol alcanza 60 a 70 metros de altura, con un tronco grueso que puede llegar a medir más de 3 m de diámetro, con raíces tabulares. El tronco y muchas de sus ramas mayores están densamente pobladas de espinas largas y robustas. Las hojas están divididas en 5 a 9 folíolos más pequeños, cada hoja sobrepasa los 20 cm. Los árboles adultos producen varios cientos de frutos, cápsulas dehiscentes de unos 15 cm (a veces mal llamadas vainas, que es otro fruto diferente). Las cápsulas contienen semillas que se encuentran rodeadas por una fibra amarillenta de aspecto algodonoso, que es una mezcla de lignina y de celulosa.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('10', 'Fresno', 'imagenes/Flora/fresno.jpg', 'Son arbustos a árboles grandes; plantas dioicas o poligamodioicas. Hojas alternas, imparipinnadas, raramente paripinnadas, siempreverdes; folíolos opuestos o a veces subopuestos, peciolulados, márgenes enteros. Inflorescencias subterminales, paniculadas, las últimas ramas a veces espigadas; flores pediceladas o sésiles, 5-meras, imbricadas, corola amarillo verdosa, amarilla o color crema; estambres (8–) 10, en 2 series (a veces marcadamente) desiguales, filamentos lineares a subulados; disco intrastaminal 5–10-lobado; ovario 1-locular, densamente pubescente, el único óvulo apical o subapicalmente suspendido, estilos (4–) 5, libres, estigmas capitados.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('11', 'Helechos', 'imagenes/Flora/helechos.jpg', 'son plantas vasculares sin semilla (pteridofitas), cuyas características morfológicas más sobresalientes son sus hojas grandes (\"megafilos\" o \"frondes\"), usualmente pinadas y con prefoliación circinada. Tradicionalmente ha agrupado a 3 gruposː los helechos leptosporangiados (Polypodiidae), maratiales y ofioglosales, sin embargo, los análisis genéticos modernos encontraron que los ofioglosales están relacionados con los psilotales, los cuales históricamente se clasificaron aparte al considerárseles primitivos, agrupándose ahora juntos en un solo taxón llamado Ophioglossidae o Psilotopsida.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('12', 'Nectandra', 'imagenes/Flora/Nectandra.jpg', 'Son árboles o arbustos; hermafroditas. Las hojas alternas, enteras, glabras o con pubescencia variada, pinnatinervias. Las inflorescencias axilares o pseudoterminales, paniculadas, las últimas divisiones cimosas, mayormente algo pubescentes, las floresson pequeñas, raramente más de 1 cm de diámetro, blancas o verdosas; tépalos iguales. El fruto es una baya asentada sobre una cúpula poco profunda.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('13', 'Mangle', 'imagenes/Flora/mangle.jpg', 'es un arbusto o árbol leñoso, perteneciente a las rizoforáceas. Tiene frutos, de tres a cuatro metros de altura, aunque a veces alcanza unos 15 metros o más. Sus ramas largas y extendidas dan vástagos que descienden hasta tocar el suelo y arraigar en él. Tiene hojas pecioladas, opuestas, enteras, elípticas, obtusas y gruesas; flores axilares de cuatro pétalos amarillentos; fruto seco de corteza coriácea, pequeño y casi redondo y muchas raíces externas en parte. Los mangles forman ecosistemas, llamados manglares.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('14', 'Mangle negro', 'imagenes/Flora/mangle_negro.jpg', 'Es un árbol o arbusto que alcanza un tamaño de 3–10 m de alto. Tiene hojas angostas, elíptico-oblongas, de 6,5–10 cm de largo y 1,5–3 cm de ancho, con ápice agudo (agudo-redondeado), y base cuneada. Inflorescencia en forma de panícula de espigas 1 (2)-compuesta, de 9 cm de largo y 2–5 cm de ancho, flores agrupadas en los extremos, bráctea floral ovada, de 2,5–3 mm de largo, bractéolas lanceoladas, de 2,5–4 mm de largo; cáliz de 3,5–4,5 mm de largo; corola de 4,5–8 mm de largo; estambres con anteras exertas, filamentos de 2,5–4 mm de largo, todos similares y filiformes. Fruto ovado-oblicuo, apiculado, de 1,5–2 cm de largo y 1–1,5 cm de ancho, escasamente seríceo.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('15', 'Mangle blanco', 'imagenes/Flora/mangle_blanco.jpg', 'Son arbustos o árboles, que alcanzan un tamaño de hasta 15 m de alto, con raíces zancudas y frecuentemente con neumatóforos; plantas mayormente hermafroditas pero a menudo andromonoicas y a veces dioicas.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('16', 'Mangle piñuelo', 'imagenes/Flora/mangle_piñuelo.jpg', 'Son árboles generalmente siempreverdes; plantas hermafroditas. Hojas alternas, simples, nervadura pinnada, nervios secundarios inconspicuos; sin estípulas. Flores solitarias, axilares (de apariencia terminal), regulares, cada una abrazada por 2 bractéolas; sépalos 5, libres, imbricados, caducos; pétalos 5, libres, imbricados; estambres 5, libres, alternos con los pétalos, adpresos en las ranuras del ovario, anteras abriéndose longitudinalmente, conectivo prolongado; ovario súpero, con 2 carpelos unidos, 2-locular, placentación axial, 1 óvulo por lóculo (uno de ellos vacío), un estilo con estigma punctiforme. Fruto seco y coriáceo, indehiscente con 1 lóculo y 1 semilla.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('17', 'Mangle rojo', 'imagenes/Flora/mangle_rojo.jpg', 'Es un árbol que alcanza un tamaño de hasta 20 m de alto. Tiene las hojas elípticas, de 11–15 cm de largo y 4–7 cm de ancho, el ápice agudo, la base cuneada, glabras, envés con puntos negros. La inflorescencia de 5–12 cm de largo, 3–5 veces ramificada, con numerosas flores, pedúnculo de 2–7 cm de largo, con brácteas gruesas, bífidas; pedicelos 3–11 mm de largo, flores 1 cm de largo; estambres 8; yema floral ovada o ligeramente elíptica, ápice agudo. Fruto ovado-lanceolado, 4 cm de largo y 1.5 cm de ancho, radícula 11–25 cm de largo.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('18', 'Miconia', 'imagenes/Flora/Miconia.jpg', 'Arbustos o árboles hasta 20 m de alto con un diámetro hasta de 50 cm, tronco derecho, a veces con chupones, copa redondeada y ramas ascendentes. La corteza externa es escamosa que se desprende en tiras largas irregulares de color gris pardusco o amarillenta ligeramente rojiza. Las ramas jóvenes, pecíolos, envés, inflorescencias e hipanto cubierto por un denso tomento estrellado pardo claro, los entrenudos distales marcadamente aplanados y con 2 bordes. ');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('19', 'Mora oleifera', 'imagenes/Flora/mora_oleifera.jpg', 'Son árboles, que alcanzan un tamaño de hasta 45 m de alto, inermes, con grandes contrafuertes, corteza café-rojiza. Hojas 1-pinnadas; folíolos 2 o 3 pares, elípticos a elíptico-oblongos, 8–18 cm de largo y 4–7 cm de ancho, ápice agudo-acuminado, base redondeada a obtusa, glabros, coriáceos o subcoriáceos, reticulados, no punteado-glandulares, peciólulos 2–3 mm de largo, acanalados a planos; raquis plano en el lado abaxial, estípulas caducas. Inflorescencias panículas terminales o subterminales de espigas, 7–10 cm de largo, glabras, con numerosas flores pequeñas, blancas, sésiles; cáliz campanulado con un tubo corto, lobos 5, 3–4 mm de largo, apicalmente redondeados, imbricados, ciliados; pétalos 5, oblongos, imbricados, 5–6 mm de largo y 2.5–3 mm de ancho; estambres 5, libres, distalmente lanosos, alternando con 5 estaminodios apicalmente dilatados; ovario subsésil, lanoso, óvulos 2 o 3, estilo corto, glabro, estigma terminal, pequeño. Fruto oblongo, hasta 25 cm de largo y 10–13 cm de ancho, valvas leñosas, lisas a subverrugosas, dehiscente; semilla 1 (2), reniforme, hasta 18 cm de largo y 12 cm de ancho, testa delgada.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('20', 'Palma areacáceas', 'imagenes/Flora/Palma_arecáceas.jpg', 'es una familia de plantas monocotiledóneas, la única familia del orden Arecales (sinónimo Principales). Normalmente se las conoce como palmeras o palmas. Los individuos de esta importante familia son fáciles de reconocer visualmente, aunque puede haber confusión con especies de las familias Cycadaceae y Zamiaceae debido a las similitudes morfológicas. Son plantas leñosas (pero sin crecimiento secundario del tronco, solo primario). A pesar de ser monocotiledóneas muchas de ellas son arborescentes, con grandes hojas en corona al final del tallo, generalmente pinnadas (pinnatisectas) o palmadas (palmatisectas). Sus flores poseen 3 sépalos y 3 pétalos, y se disponen en inflorescencias provistas de una o varias espatas. El fruto es carnoso: una baya o una drupa. Están ampliamente distribuidas en regiones tropicales a templadas, pero principalmente en regiones cálidas.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('21', 'Palma de seje', 'imagenes/Flora/Palma_seje.jpg', 'Es una palma abundante en zonas húmedas y pluviales a menos de 1000 msnm al noroccidente de Sudamérica desde Panamá hasta el sur de América tropical. Se distribuye por Panamá, Venezuela, Colombia, Bolivia, Ecuador y Perú.2 Entre otros lugares, es autóctona del Municipio Cedeño (Bolívar), Estado Bolívar, Venezuela, cuyo fruto forma parte de la tradición culinaria de la regiones  .Se caracteriza por un estípite (tallo) solitario erecto, de 10 a 25 m de altura y 20 a 30 cm de diámetro, liso, conspicuamente anillado. Tiene de 10 a 16 hojas terminales, penduladas hacia los lados, con peciolo de 1 a 50 cm y raquis de 3 a 7 m de longitud; ápice acuminado, limbo pinnado, pinnas alternas de hasta 2 m de largo y 15 cm de ancho, aproximadamente 100 a cada lado, colocadas en un mismo plano.');
INSERT INTO `reservanatural`.`flora` (`idflora`, `Nombre`, `Imagen`, `Descripcion`) VALUES ('22', 'Palma de asaí', 'imagenes/Flora/palma_asaí.jpg', 'es una palmera nativa del norte de Sudamérica, apreciada por las propiedades nutritivas de su fruto. También se conoce con el nombre de palma manaca.');


CREATE TABLE `reservanatural`.`contactenos` (
  `idcontactenos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontactenos`));
  
  INSERT INTO `reservanatural`.`contactenos` (`idcontactenos`, `Nombre`, `Telefono`, `Correo`) VALUES ('1', 'Carlos Taborda', '3136545076', 'carlitos123@gmail.com');
  INSERT INTO `reservanatural`.`contactenos` (`idcontactenos`, `Nombre`, `Telefono`, `Correo`) VALUES ('2', 'Gloria Zapata', '12315232', 'gloria2352@gmal.com');
  INSERT INTO `reservanatural`.`contactenos` (`idcontactenos`, `Nombre`, `Telefono`, `Correo`) VALUES ('3', 'Reserva De Utria', '5808266', 'reservanaturaldeutria1@gmail.com');

